import { palletFormError, palletFormValue } from "../interfaces/forms";

export const defaultPalletForm: palletFormValue = {
  length: NaN,
  palletOpening: NaN,
  width: NaN,
  height: NaN,
  stringerLength: NaN,
  stringerWidth: NaN,
  stringerBoardLength: NaN,
  stringerBoardWidth: NaN,
  stringerBoardHeight: NaN,
  topBoardPlanks: NaN,
  bottomBoardPlanks: NaN,
  stringerBoardNumber: NaN,
  stringerNumber: NaN,
  topPlankLength: NaN,
  topPlankdWidth: NaN,
  topPlankHeight: NaN,
  bottomPlankLength: NaN,
  bottomPlankdWidth: NaN,
  bottomPlankHeight: NaN,
  blockLength: NaN,
  blockdWidth: NaN,
  blockNumbers: NaN,
  name: "",
  email: "",
  requirement: NaN,
  remarks: "",
  capacity: "500",
  type: "four-way",
};

export const defaultPalletFormError: palletFormError = {
  length: "",
  palletOpening: "",
  width: "",
  height: "",
  stringerLength: "",
  stringerWidth: "",
  stringerBoardLength: "",
  stringerBoardWidth: "",
  stringerBoardHeight: "",
  topBoardPlanks: "",
  bottomBoardPlanks: "",
  stringerBoardNumber: "",
  stringerNumber: "",
  topPlankLength: "",
  topPlankdWidth: "",
  topPlankHeight: "",
  bottomPlankLength: "",
  bottomPlankdWidth: "",
  bottomPlankHeight: "",
  blockLength: "",
  blockdWidth: "",
  blockNumbers: "",
  name: "",
  email: "",
  requirement: "",
  remarks: "",
};

export const heights = {
  "500": 51,
  "1000": 60.6,
  "1500": 70,
  "2000": 76,
  "3000": 95.6,
};
